
project_id = "CRM-app"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[functions.send-email]
enabled = true

[functions.send-order-email]
enabled = true
