
project_id = 'pxhvrmmmllcsjliupync'

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"

[realtime]
enabled = true

[functions.send-order-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-meeting-email]
verify_jwt = false

[functions.scan-business-card]
verify_jwt = false
