
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuowdnfywilmmwkiyvdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1b3dkbmZ5d2lsbW13a2l5dmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNjc5MDksImV4cCI6MjA5MTk0MzkwOX0.4aMgr3xLPfzx1myIEWinPBxmNAyKhHNAgtvZ-7BR_BY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
