// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxhvrmmmllcsjliupync.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4aHZybW1tbGxjc2psaXVweW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjYyNTgsImV4cCI6MjA1ODM0MjI1OH0.yzj9a9zSTIIAGuqRQ-54Nf4iKcvTlVsuJLppaP1L1og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);